### ISSUE TITLE
Add text field

### ISSUE THREAD

**Issue by RabinaRokaa** [BivekKarkii/WaterBillingSystem#8]
There appears to be a missing text field in the consumer registration form, so it is recommended to include this text field " Consumer Id" in the registration form.

**Comment by Nilimanili** [comment]
Thank you for the suggestion. I'll check for  the correction

**Comment by Nilimanili** [comment]
I sloved the issues that were created.and i added a missing text field in the consumer registration form, as per the  recommendation  registration form.
